In [5]:
%config InlineBackend.figure_format = 'retina'
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Format data

In [6]:
cov = pd.read_csv('covtype.csv')
cov = cov.sample(n=20000, replace=False)

In [13]:
cov = cov.reset_index(drop=True)
cov = cov.drop(columns=['index'])
print(cov.shape)
cov.head()

(20000, 55)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2862,166,12,30,-2,4821,230,244,144,108,...,0,0,0,0,0,0,0,0,0,2
1,2903,18,2,150,0,4868,217,234,154,4777,...,0,0,0,0,0,0,0,0,0,2
2,3093,125,16,360,38,582,245,228,107,1332,...,1,0,0,0,0,0,0,0,0,1
3,2392,127,14,417,77,495,242,230,114,1082,...,0,0,0,0,0,0,0,0,0,3
4,2993,198,11,569,48,2060,217,249,166,2398,...,1,0,0,0,0,0,0,0,0,2

In [14]:
cov['Cover_Type'].value_counts()

2    9675
1    7346
3    1206
7     713
6     603
5     362
4      95
Name: Cover_Type, dtype: int64

In [16]:
class0_vals = [1, 3, 4, 5, 6, 7]
class1_vals = [2]
class0 = cov.loc[cov['Cover_Type'].isin(class0_vals)]
class1 = cov.loc[cov['Cover_Type'].isin(class1_vals)]
print(class1.shape)
print(class0.shape)
class1.head()

(9675, 55)
(10325, 55)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2862,166,12,30,-2,4821,230,244,144,108,...,0,0,0,0,0,0,0,0,0,2
1,2903,18,2,150,0,4868,217,234,154,4777,...,0,0,0,0,0,0,0,0,0,2
4,2993,198,11,569,48,2060,217,249,166,2398,...,1,0,0,0,0,0,0,0,0,2
7,2682,62,22,124,40,1706,232,188,77,1215,...,0,0,0,0,0,0,0,0,0,2
9,2896,59,11,201,21,1765,228,217,120,2230,...,0,0,0,0,0,0,0,0,0,2

In [18]:
class0.loc[:,'Cover_Type'] = 0
class1.loc[:,'Cover_Type'] = 1
# class1.loc['']
class1.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2862,166,12,30,-2,4821,230,244,144,108,...,0,0,0,0,0,0,0,0,0,1
1,2903,18,2,150,0,4868,217,234,154,4777,...,0,0,0,0,0,0,0,0,0,1
4,2993,198,11,569,48,2060,217,249,166,2398,...,1,0,0,0,0,0,0,0,0,1
7,2682,62,22,124,40,1706,232,188,77,1215,...,0,0,0,0,0,0,0,0,0,1
9,2896,59,11,201,21,1765,228,217,120,2230,...,0,0,0,0,0,0,0,0,0,1

In [20]:
cov = class0.append(class1)
cov = cov.rename(columns={'Cover_Type': 'Y'})
cov['Y'].value_counts()

0    10325
1     9675
Name: Y, dtype: int64

In [22]:
cov.to_csv('cov_formatted.csv', index=False)

## Create 5 Trials - Training and Testing Sets

In [24]:
from sklearn.model_selection import train_test_split

XY_train1, XY_test1 = train_test_split(cov, train_size=5000, shuffle=True)
XY_train2, XY_test2 = train_test_split(cov, train_size=5000, shuffle=True)
XY_train3, XY_test3 = train_test_split(cov, train_size=5000, shuffle=True)
XY_train4, XY_test4 = train_test_split(cov, train_size=5000, shuffle=True)
XY_train5, XY_test5 = train_test_split(cov, train_size=5000, shuffle=True)

In [25]:
print(XY_train1.shape)
print(XY_test1.shape)
XY_train1.head()

(5000, 55)
(15000, 55)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Y
10110,2997,118,15,342,66,2413,244,226,106,1405,...,0,0,1,0,0,0,0,0,0,1
8688,3257,124,12,30,7,787,240,231,118,1243,...,0,0,0,0,0,0,0,0,0,1
8516,3029,353,12,124,39,1277,199,218,157,1377,...,1,0,0,0,0,0,0,0,0,1
16562,3456,245,19,495,146,3496,178,251,208,942,...,0,0,0,0,0,0,0,1,0,0
7205,3070,237,10,384,66,5798,203,249,183,4348,...,0,0,0,0,0,0,0,0,0,1

## Run GridSearchCV on classifier

In [26]:
%%time
#import warnings
# there are a lot of convergence warnings for some params, however be careful with this!!
# sometimes you need to see those wanrings, and now we've screwed tha tup for the whole notebook from here on!!
#warnings.filterwarnings('ignore')

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression 
import numpy as np
from sklearn.model_selection import GridSearchCV

# Create a pipeline - RF is a stand in, we will populate the classifier part below
pipe = Pipeline([('std', StandardScaler()),
                 ('classifier', LogisticRegression())])

# Create search space of candidate learning algorithms and their hyperparameters
# note lbfgs can't do l1, and if you pass penalty='none' it expects no C value
search_space = [{'classifier': [LogisticRegression(max_iter=5000)],
                 'classifier__solver': ['saga'],
                 'classifier__penalty': ['l1', 'l2'],
                 'classifier__C': np.logspace(-4, 4, 9)},
                {'classifier': [LogisticRegression(max_iter=5000)],
                 'classifier__solver': ['lbfgs'],
                 'classifier__penalty': ['l2'],
                 'classifier__C': np.logspace(-4, 4, 9)},
                {'classifier': [LogisticRegression(max_iter=5000)],
                 'classifier__solver': ['lbfgs','saga'],
                 'classifier__penalty': ['none']}
                ]

trialnum = 0
accuracy_sum = 0 # sum of top accuracy to later calculate the average of all 5 trials
roc_sum = 0 # sum of top roc score to later calculate the average of all 5 trials
f1_sum = 0 # sum of top accuracy to later calculate the average of all 5 trials
accuracy_scores = []
roc_scores = []
f1_scores = []
all_accuracy_models = []
all_roc_models = []
all_f1_models = []

# for every trial
for trial in [XY_train1, XY_train2, XY_train3, XY_train4, XY_train5]:
 
    trialnum = trialnum + 1
    X_l = trial.drop(['Y'],1)
    y_l = trial['Y']
    
    # Create grid search 
    clf = GridSearchCV(pipe, search_space, cv=StratifiedKFold(n_splits=5), 
                       scoring=['accuracy', 'roc_auc_ovr', 'f1_micro'], refit=False,
                       verbose=0)

    # Fit grid search
    best_model = clf.fit(X_l, y_l)
    
    print("------------------------------------------------------------------------------------")
    print("RESULTS FOR TRIAL:")
    print(trialnum)
    print("------------------------------------------------------------------------------------")
    
    # the detailed results of the whole model selection search...
#     print(best_model.cv_results_)

    print("---------------BEST MODEL FOR ACCURACY: ----------")
    print( best_model.cv_results_['params'][ np.argmin(best_model.cv_results_['rank_test_accuracy']) ] )
    print("---WITH ACCURACY: ---")
    current_accuracy = best_model.cv_results_['mean_test_accuracy'][ np.argmax(best_model.cv_results_['mean_test_accuracy']) ]
    print(current_accuracy)
    accuracy_sum = accuracy_sum + current_accuracy
    accuracy_scores.append(current_accuracy)
    all_accuracy_models.append( best_model.cv_results_['params'][ np.argmin(best_model.cv_results_['rank_test_accuracy']) ] )
    
    print("---------------BEST MODEL FOR ROC: ---------------")
    print( best_model.cv_results_['params'][ np.argmin(best_model.cv_results_['rank_test_roc_auc_ovr']) ] )
    print("---WITH ROC: ---")
    current_roc = best_model.cv_results_['mean_test_roc_auc_ovr'][ np.argmax(best_model.cv_results_['mean_test_roc_auc_ovr']) ]
    print(current_roc)
    roc_sum = roc_sum + current_roc
    roc_scores.append(current_roc)
    all_roc_models.append( best_model.cv_results_['params'][ np.argmin(best_model.cv_results_['rank_test_roc_auc_ovr']) ] )

    
    print("---------------BEST MODEL FOR F1: ----------------")
    print( best_model.cv_results_['params'][ np.argmin(best_model.cv_results_['rank_test_f1_micro']) ] )
    print("---WITH F1: ---")    
    current_f1 = best_model.cv_results_['mean_test_f1_micro'][ np.argmax(best_model.cv_results_['mean_test_f1_micro']) ]
    print(current_f1)
    f1_sum = f1_sum + current_f1
    f1_scores.append(current_f1)
    all_f1_models.append( best_model.cv_results_['params'][ np.argmin(best_model.cv_results_['rank_test_f1_micro']) ] )

------------------------------------------------------------------------------------
RESULTS FOR TRIAL:
1
------------------------------------------------------------------------------------
---------------BEST MODEL FOR ACCURACY: ----------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH ACCURACY: ---
0.7538
---------------BEST MODEL FOR ROC: ---------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 1.0, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH ROC: ---
0.823655406831449
---------------BEST MODEL FOR F1: ----------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH F1: ---
0.7538
------------------------------------------------------------------------------------
RESULTS FOR TRIAL:
2
------------------------------------------------------------------------------------
---------------BEST MODEL FOR ACCURACY: ----------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH ACCURACY: ---
0.7494
---------------BEST MODEL FOR ROC: ---------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH ROC: ---
0.8187022964313085
---------------BEST MODEL FOR F1: ----------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH F1: ---
0.7494
------------------------------------------------------------------------------------
RESULTS FOR TRIAL:
3
------------------------------------------------------------------------------------
---------------BEST MODEL FOR ACCURACY: ----------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 1.0, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH ACCURACY: ---
0.7516
---------------BEST MODEL FOR ROC: ---------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 1.0, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH ROC: ---
0.8233668916665664
---------------BEST MODEL FOR F1: ----------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 1.0, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH F1: ---
0.7516
------------------------------------------------------------------------------------
RESULTS FOR TRIAL:
4
------------------------------------------------------------------------------------
---------------BEST MODEL FOR ACCURACY: ----------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH ACCURACY: ---
0.7578
---------------BEST MODEL FOR ROC: ---------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 1.0, 'classifier__penalty': 'l2', 'classifier__solver': 'saga'}
---WITH ROC: ---
0.8260869373761903
---------------BEST MODEL FOR F1: ----------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH F1: ---
0.7578
------------------------------------------------------------------------------------
RESULTS FOR TRIAL:
5
------------------------------------------------------------------------------------
---------------BEST MODEL FOR ACCURACY: ----------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH ACCURACY: ---
0.7562
---------------BEST MODEL FOR ROC: ---------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH ROC: ---
0.823636531150982
---------------BEST MODEL FOR F1: ----------------
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
---WITH F1: ---
0.7562
Wall time: 36min 45s

### Get Train metrics

In [27]:
print("===== ACCURACY SCORES: =====")
print(accuracy_scores)
print("===== ROC SCORES: =====")
print(roc_scores)
print("===== F1 SCORES: =====")
print(f1_scores)

===== ACCURACY SCORES: =====
[0.7538, 0.7494, 0.7516, 0.7578, 0.7562]
===== ROC SCORES: =====
[0.823655406831449, 0.8187022964313085, 0.8233668916665664, 0.8260869373761903, 0.823636531150982]
===== F1 SCORES: =====
[0.7538, 0.7494, 0.7516, 0.7578, 0.7562]

In [28]:
print("================ BEST ACCURACY MODEL IN TRAINING: ==================")
print(all_accuracy_models[ np.argmax(accuracy_scores) ])
print("WITH ACCURACY:")
print(max(accuracy_scores))
print("================ BEST ROC MODEL IN TRAINING: ==================")
print(all_roc_models[ np.argmax(roc_scores) ])
print("WITH ROC SCORE:")
print(max(roc_scores))
print("================ BEST F1 MODEL IN TRAINING: ==================")
print(all_f1_models[ np.argmax(f1_scores) ])
print("WITH F1 SCORE:")
print(max(f1_scores))

================ BEST ACCURACY MODEL IN TRAINING: ==================
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
WITH ACCURACY:
0.7578
================ BEST ROC MODEL IN TRAINING: ==================
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 1.0, 'classifier__penalty': 'l2', 'classifier__solver': 'saga'}
WITH ROC SCORE:
0.8260869373761903
================ BEST F1 MODEL IN TRAINING: ==================
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
WITH F1 SCORE:
0.7578

In [29]:
print("================ AVERAGE ACCURACY ON TRAIN SET: ==================")
print(accuracy_sum / 5)
print("================ AVERAGE ROC SCORE ON TRAIN SET: ==================")
print(roc_sum / 5)
print("================ AVERAGE F1 SCORE ON TRAIN SET: ==================")
print(f1_sum / 5)

================ AVERAGE ACCURACY ON TRAIN SET: ==================
0.7537600000000001
================ AVERAGE ROC SCORE ON TRAIN SET: ==================
0.8230896126912993
================ AVERAGE F1 SCORE ON TRAIN SET: ==================
0.7537600000000001

### Get Test metrics

In [33]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score

# test performance of model rated as best for accuracy and f1 score on training set
performance_AccModel = pd.DataFrame(index=['acc', 'roc', 'f1'], columns=['Trial 1', 'Trial 2', 'Trial 3', 'Trial 4', 'Trial 5'])
performance_AccModel

# test performance on trial 1 test set
clf = LogisticRegression(penalty='l1', C=0.1, solver='saga', max_iter=10000).fit(XY_train1.drop(['Y'],1), XY_train1['Y'])
pred = clf.predict(XY_test1.drop(['Y'],1))
performance_AccModel.loc['acc', 'Trial 1'] = accuracy_score(XY_test1['Y'], pred)
performance_AccModel.loc['roc', 'Trial 1'] = roc_auc_score(XY_test1['Y'], pred)
performance_AccModel.loc['f1', 'Trial 1'] = f1_score(XY_test1['Y'], pred)

# test performance on trial 2 test set
clf = LogisticRegression(penalty='l1', C=0.1, solver='saga', max_iter=10000).fit(XY_train2.drop(['Y'],1), XY_train2['Y'])
pred = clf.predict(XY_test2.drop(['Y'],1))
performance_AccModel.loc['acc', 'Trial 2'] = accuracy_score(XY_test2['Y'], pred)
performance_AccModel.loc['roc', 'Trial 2'] = roc_auc_score(XY_test2['Y'], pred)
performance_AccModel.loc['f1', 'Trial 2'] = f1_score(XY_test2['Y'], pred)

# test performance on trial 3 test set
clf = LogisticRegression(penalty='l1', C=0.1, solver='saga', max_iter=10000).fit(XY_train3.drop(['Y'],1), XY_train3['Y'])
pred = clf.predict(XY_test3.drop(['Y'],1))
performance_AccModel.loc['acc', 'Trial 3'] = accuracy_score(XY_test3['Y'], pred)
performance_AccModel.loc['roc', 'Trial 3'] = roc_auc_score(XY_test3['Y'], pred)
performance_AccModel.loc['f1', 'Trial 3'] = f1_score(XY_test3['Y'], pred)

# test performance on trial 4 test set
clf = LogisticRegression(penalty='l1', C=0.1, solver='saga', max_iter=10000).fit(XY_train4.drop(['Y'],1), XY_train4['Y'])
pred = clf.predict(XY_test4.drop(['Y'],1))
performance_AccModel.loc['acc', 'Trial 4'] = accuracy_score(XY_test4['Y'], pred)
performance_AccModel.loc['roc', 'Trial 4'] = roc_auc_score(XY_test4['Y'], pred)
performance_AccModel.loc['f1', 'Trial 4'] = f1_score(XY_test4['Y'], pred)

# test performance on trial 5 test set
clf = LogisticRegression(penalty='l1', C=0.1, solver='saga', max_iter=10000).fit(XY_train5.drop(['Y'],1), XY_train5['Y'])
pred = clf.predict(XY_test5.drop(['Y'],1))
performance_AccModel.loc['acc', 'Trial 5'] = accuracy_score(XY_test5['Y'], pred)
performance_AccModel.loc['roc', 'Trial 5'] = roc_auc_score(XY_test5['Y'], pred)
performance_AccModel.loc['f1', 'Trial 5'] = f1_score(XY_test5['Y'], pred)

performance_AccModel

      Trial 1   Trial 2   Trial 3   Trial 4   Trial 5
acc  0.624933  0.618867    0.6152    0.6228  0.620133
roc  0.623332  0.616824  0.613419  0.620899  0.618421
f1   0.597395  0.581999  0.582827  0.590949  0.589422

In [31]:
# test performance of model rated as best for roc on training set
performance_ROCModel = pd.DataFrame(index=['acc', 'roc', 'f1'], columns=['Trial 1', 'Trial 2', 'Trial 3', 'Trial 4', 'Trial 5'])

# test performance on trial 1 test set
clf = LogisticRegression(penalty='l2', C=177.82794100389228, solver='lbfgs', max_iter=10000).fit(XY_train1.drop(['Y'],1), XY_train1['Y'])
pred = clf.predict(XY_test1.drop(['Y'],1))
performance_ROCModel.loc['acc', 'Trial 1'] = accuracy_score(XY_test1['Y'], pred)
performance_ROCModel.loc['roc', 'Trial 1'] = roc_auc_score(XY_test1['Y'], pred)
performance_ROCModel.loc['f1', 'Trial 1'] = f1_score(XY_test1['Y'], pred)

# test performance on trial 2 test set
clf = LogisticRegression(penalty='l2', C=177.82794100389228, solver='lbfgs', max_iter=10000).fit(XY_train2.drop(['Y'],1), XY_train2['Y'])
pred = clf.predict(XY_test2.drop(['Y'],1))
performance_ROCModel.loc['acc', 'Trial 2'] = accuracy_score(XY_test2['Y'], pred)
performance_ROCModel.loc['roc', 'Trial 2'] = roc_auc_score(XY_test2['Y'], pred)
performance_ROCModel.loc['f1', 'Trial 2'] = f1_score(XY_test2['Y'], pred)

# test performance on trial 3 test set
clf = LogisticRegression(penalty='l2', C=177.82794100389228, solver='lbfgs', max_iter=10000).fit(XY_train3.drop(['Y'],1), XY_train3['Y'])
pred = clf.predict(XY_test3.drop(['Y'],1))
performance_ROCModel.loc['acc', 'Trial 3'] = accuracy_score(XY_test3['Y'], pred)
performance_ROCModel.loc['roc', 'Trial 3'] = roc_auc_score(XY_test3['Y'], pred)
performance_ROCModel.loc['f1', 'Trial 3'] = f1_score(XY_test3['Y'], pred)

# test performance on trial 4 test set
clf = LogisticRegression(penalty='l2', C=177.82794100389228, solver='lbfgs', max_iter=10000).fit(XY_train4.drop(['Y'],1), XY_train4['Y'])
pred = clf.predict(XY_test4.drop(['Y'],1))
performance_ROCModel.loc['acc', 'Trial 4'] = accuracy_score(XY_test4['Y'], pred)
performance_ROCModel.loc['roc', 'Trial 4'] = roc_auc_score(XY_test4['Y'], pred)
performance_ROCModel.loc['f1', 'Trial 4'] = f1_score(XY_test4['Y'], pred)

# test performance on trial 5 test set
clf = LogisticRegression(penalty='l2', C=177.82794100389228, solver='lbfgs', max_iter=10000).fit(XY_train5.drop(['Y'],1), XY_train5['Y'])
pred = clf.predict(XY_test5.drop(['Y'],1))
performance_ROCModel.loc['acc', 'Trial 5'] = accuracy_score(XY_test5['Y'], pred)
performance_ROCModel.loc['roc', 'Trial 5'] = roc_auc_score(XY_test5['Y'], pred)
performance_ROCModel.loc['f1', 'Trial 5'] = f1_score(XY_test5['Y'], pred)

performance_ROCModel

      Trial 1   Trial 2   Trial 3   Trial 4   Trial 5
acc  0.727067    0.7452  0.742133  0.747467  0.747667
roc  0.727314   0.74557  0.742816  0.747782     0.748
f1   0.722252  0.742903  0.742202  0.743534  0.744585

## Get final Logistic Regression results

In [32]:
print("================ BEST ACCURACY MODEL IN LOGISTIC REGRESSION: ==================")
print(all_accuracy_models[ np.argmax(np.array(performance_AccModel.iloc[0])) ])
print("WITH ACCURACY:")
print((np.array(performance_AccModel.iloc[0])).mean())
print("================ BEST ROC MODEL IN LOGISTIC REGRESSION: ==================")
print(all_roc_models[ np.argmax(np.array(performance_ROCModel.iloc[1])) ])
print("WITH ROC SCORE:")
print((performance_ROCModel.iloc[1]).mean())
print("================ BEST F1 MODEL IN LOGISTIC REGRESSION: ==================")
print(all_f1_models[ np.argmax(np.array(performance_AccModel.iloc[2])) ])
print("WITH F1 SCORE:")
print((np.array(performance_AccModel.iloc[2])).mean())

================ BEST ACCURACY MODEL IN LOGISTIC REGRESSION: ==================
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
WITH ACCURACY:
0.6187333333333334
================ BEST ROC MODEL IN LOGISTIC REGRESSION: ==================
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
WITH ROC SCORE:
0.7422963710164352
================ BEST F1 MODEL IN LOGISTIC REGRESSION: ==================
{'classifier': LogisticRegression(max_iter=5000), 'classifier__C': 0.1, 'classifier__penalty': 'l1', 'classifier__solver': 'saga'}
WITH F1 SCORE:
0.5864970951385085